import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI, HarmCategory, HarmBlockThreshold } from "@google/genai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 8080;

// Middleware to parse JSON bodies
app.use(express.json());

// Initialize Gemini Client (Server-side only)
const apiKey = process.env.API_KEY;
// Log warning if key is missing (visible in server logs, not client)
if (!apiKey) {
  console.warn("WARNING: API_KEY is not set in the server environment.");
}
const ai = new GoogleGenAI({ apiKey: apiKey || 'dummy' });

// --- API ROUTES ---

// System Instructions
const DRAFT_SYSTEM_INSTRUCTION = `
You are a professional DOTA 2 analyst and coach (like Ceb or Notail).
Your task is to analyze two team compositions (Radiant vs Dire).
1. Predict the win probability.
2. Identify the win conditions for Radiant.
3. Suggest key items for the Radiant team to counter Dire.
4. Keep it concise, strategic, and use DOTA 2 terminology (e.g., "BKB", "power spike", "roshan control").
Format the output with Markdown headers.
`;

const LORE_SYSTEM_INSTRUCTION = `
You are the Shopkeeper from the Secret Shop in DOTA 2. 
You are mysterious, ancient, and knowledgeable about the lore of the Ancients.
Answer questions about hero backstories, item lore, and the history of the world.
Speak in a slightly archaic, mystical tone.
`;

const safetySettings = [
  {
    category: HarmCategory.HARM_CATEGORY_HARASSMENT,
    threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH,
  },
];

// Endpoint: Analyze Draft
app.post('/api/analyze', async (req, res) => {
  try {
    const { radiant, dire, lang, userContext } = req.body;
    
    if (!apiKey) {
        return res.status(500).json({ error: "Server API Key not configured" });
    }

    const radiantNames = radiant.map(h => h.name).join(', ');
    const direNames = dire.map(h => h.name).join(', ');
    
    const langInstruction = lang === 'zh' 
      ? '请使用中文(简体)进行回答。' 
      : 'Please answer in English.';

    const prompt = `
      Analyze this DOTA 2 Matchup:
      **Radiant:** ${radiantNames || 'None'}
      **Dire:** ${direNames || 'None'}
      
      **Additional Context/Strategy from User:** ${userContext || 'None'}

      If teams are incomplete, provide general advice for the heroes present.
      ${langInstruction}
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        systemInstruction: DRAFT_SYSTEM_INSTRUCTION,
        temperature: 0.7,
        safetySettings,
      },
    });

    res.json({ text: response.text });
  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
});

// Endpoint: Chat
app.post('/api/chat', async (req, res) => {
  try {
    const { history, message, lang } = req.body;

    if (!apiKey) {
        return res.status(500).json({ error: "Server API Key not configured" });
    }

    const langInstruction = lang === 'zh' 
      ? '请使用中文(简体)回答所有问题。' 
      : 'Please answer in English.';

    // Append language instruction to the system instruction dynamically for this chat
    // Note: Since we create a new chat instance per request in this stateless wrapper, 
    // we can just mix it into system instruction or the message. 
    // Mixing into system instruction is cleaner.
    
    const chat = ai.chats.create({
      model: 'gemini-3-flash-preview',
      config: {
        systemInstruction: `${LORE_SYSTEM_INSTRUCTION}\n${langInstruction}`,
        temperature: 0.8,
      },
      history: history.map(h => ({
        role: h.role,
        parts: h.parts
      }))
    });

    const result = await chat.sendMessage({ message });
    res.json({ text: result.text });
  } catch (error) {
    console.error("Gemini Chat Error:", error);
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
});

// --- STATIC FILES ---

// Serve static files from the dist directory (generated by 'npm run build')
app.use(express.static(path.join(__dirname, 'dist')));

// Handle client-side routing by returning index.html for all non-api requests
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});